name:                imd18
version:             0.1.0.0
github:              nzherald/imd18
license:             BSD3
author:              Chris Knox
maintainer:          chris.knox@nzherald.co.nz
copyright:           MIT

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on Github at <https://github.com/nzherald/imd18#readme>

dependencies:
- base >= 4.11 && < 10
- rio >= 0.1.12.0
- dhall

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  other-modules: []

executables:
  imd18:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - imd18
    - optparse-generic

    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
  nzh:
    main: Shakefile.hs
    source-dirs: .
    dependencies:
    - imd18
    - dhall
    - shake
    other-modules: []